version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
